runtime: nodejs20

env_variables:
  SLACK_BOT_TOKEN: "xoxb-6885750353442-7303824565959-3xM4xydQc69ecIwNYRseuKuP"

handlers:
  - url: /.*
    script: auto

instance_class: "F1"
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.9